apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  labels:
    type: local # Sets PV's type to local
  name: postgresql-data # Sets PV's name
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi # Sets PV Volume
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volume" # Sets the volume's path
